# -*- coding: utf-8 -*-
"""Inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKyBTSy23Hq1xeiyFJg-8NuUtHcG3KuJ
"""

import mlflow
import pandas as pd

# Pastikan Anda sudah login ke DagsHub di terminal/Colab sebelumnya
# Ganti URL di bawah dengan 'Model URI' yang ada di tab Artifacts DagsHub Anda
model_uri = "models:/retail_segmentation_model/latest"
model = mlflow.pyfunc.load_model(model_uri)

# Membuat data contoh (Quantity, UnitPrice)
data_baru = pd.DataFrame([[10, 2.5]], columns=['Quantity', 'UnitPrice'])

# Melakukan prediksi
prediksi = model.predict(data_baru)
print(f"Hasil Segmentasi Cluster: {prediksi}")